var __values = (this && this.__values) || function(o) {
    var s = typeof Symbol === "function" && Symbol.iterator, m = s && o[s], i = 0;
    if (m) return m.call(o);
    if (o && typeof o.length === "number") return {
        next: function () {
            if (o && i >= o.length) o = void 0;
            return { value: o && o[i++], done: !o };
        }
    };
    throw new TypeError(s ? "Object is not iterable." : "Symbol.iterator is not defined.");
};
/**
 * Argument parser used to read from the `dist/config.json` configuration generated by the build script
 * `dash/build.js`. The argument format is "[argument]=[value]".
 */
var ArgsParser = /** @class */ (function () {
    function ArgsParser(args) {
        this.args = args;
    }
    Object.defineProperty(ArgsParser.prototype, "serverSide", {
        get: function () {
            return this.frontEnd === null;
        },
        enumerable: false,
        configurable: true
    });
    Object.defineProperty(ArgsParser.prototype, "frontEnd", {
        get: function () {
            var e_1, _a;
            try {
                for (var _b = __values(this.args), _c = _b.next(); !_c.done; _c = _b.next()) {
                    var arg = _c.value;
                    if (arg.includes('fe') || arg.includes('front-end')) {
                        return arg.split('=')[1];
                    }
                }
            }
            catch (e_1_1) { e_1 = { error: e_1_1 }; }
            finally {
                try {
                    if (_c && !_c.done && (_a = _b.return)) _a.call(_b);
                }
                finally { if (e_1) throw e_1.error; }
            }
            return null;
        },
        enumerable: false,
        configurable: true
    });
    Object.defineProperty(ArgsParser.prototype, "bola", {
        get: function () {
            return this.frontEnd == 'bola';
        },
        enumerable: false,
        configurable: true
    });
    Object.defineProperty(ArgsParser.prototype, "dynamic", {
        get: function () {
            return this.frontEnd == 'dynamic';
        },
        enumerable: false,
        configurable: true
    });
    Object.defineProperty(ArgsParser.prototype, "minerva", {
        get: function () {
            return this.frontEnd == 'minerva';
        },
        enumerable: false,
        configurable: true
    });
    Object.defineProperty(ArgsParser.prototype, "recordMetrics", {
        get: function () {
            return this.args.includes('record')
                || this.args.includes('record-metrics');
        },
        enumerable: false,
        configurable: true
    });
    Object.defineProperty(ArgsParser.prototype, "site", {
        get: function () {
            var e_2, _a;
            try {
                for (var _b = __values(this.args), _c = _b.next(); !_c.done; _c = _b.next()) {
                    var arg = _c.value;
                    if (arg.includes('www')) {
                        return arg;
                    }
                }
            }
            catch (e_2_1) { e_2 = { error: e_2_1 }; }
            finally {
                try {
                    if (_c && !_c.done && (_a = _b.return)) _a.call(_b);
                }
                finally { if (e_2) throw e_2.error; }
            }
            return null;
        },
        enumerable: false,
        configurable: true
    });
    Object.defineProperty(ArgsParser.prototype, "metricsPort", {
        get: function () {
            var e_3, _a;
            try {
                for (var _b = __values(this.args), _c = _b.next(); !_c.done; _c = _b.next()) {
                    var arg = _c.value;
                    if (arg.includes('metrics-port')) {
                        return arg.split('=')[1];
                    }
                }
            }
            catch (e_3_1) { e_3 = { error: e_3_1 }; }
            finally {
                try {
                    if (_c && !_c.done && (_a = _b.return)) _a.call(_b);
                }
                finally { if (e_3) throw e_3.error; }
            }
            return null;
        },
        enumerable: false,
        configurable: true
    });
    Object.defineProperty(ArgsParser.prototype, "quicPort", {
        get: function () {
            var e_4, _a;
            try {
                for (var _b = __values(this.args), _c = _b.next(); !_c.done; _c = _b.next()) {
                    var arg = _c.value;
                    if (arg.includes('quic-port')) {
                        return arg.split('=')[1];
                    }
                }
            }
            catch (e_4_1) { e_4 = { error: e_4_1 }; }
            finally {
                try {
                    if (_c && !_c.done && (_a = _b.return)) _a.call(_b);
                }
                finally { if (e_4) throw e_4.error; }
            }
            return null;
        },
        enumerable: false,
        configurable: true
    });
    return ArgsParser;
}());
export { ArgsParser };
//# sourceMappingURL=args.js.map